#!/usr/bin/env bash

source ./set-env

cd wrf-4.6.1

# em_real is the 3D real-data case.
./compile em_real >& compile.log

# now build the serial version for WPS
cd ../wrf-4.6.1-serial
./compile em_real >& compile.log

