#! /usr/bin/env bash

# Make sure libs are built first


#  Set env vars
source ./set-env

#  Configure wrf

#  -- Output from configure --
#  NEEDS CHECKING IF OK

# checking for perl5... no
#checking for perl... found /usr/bin/perl (perl)
#Will use NETCDF in dir: /home/ubuntu/wrf/libraries/netcdf
#ADIOS2 not set in environment. Will configure WRF for use without.
#HDF5 not set in environment. Will configure WRF for use without.
#PHDF5 not set in environment. Will configure WRF for use without.
#Will use 'time' to report timing information
#$JASPERLIB or $JASPERINC not found in environment, configuring to build without grib2 I/O...

#  33 = (smpar) GNU gcc/gfortran
#   1 = basic nesting: parent domain with one or more nested domains.
cd wrf-4.6.1
./configure << -EOF-
33
1
-EOF-

# Now configure the serial build of WRF that WPS needs
# 32 = serial
cd ../wrf-4.6.1-serial
./configure << -EOF-
32
1
-EOF-



